(define (split-at lst n)
    (define (helper lst1 n)
        (if (> n 0) (if (not (= (cdr lst1) nil))
            (list (car lst1) (helper (cdr lst1) (- n 1))))
        )
    (helper lst n)
    )
)

(define (compose-all funcs) 'YOUR-CODE-HERE)
